#!/bin/bash

## add flag -s for running in silent mode
while test $# -gt 0; do
  case "$1" in
    -s|--silent)
      SILENT=true
      shift
      ;;
    *)
      break
      ;;
  esac
done

if [ "$#" -lt 1 ]; then
  echo " ./geth-exec $NODE_NUM"
  echo "  example: "
  echo ' ./geth-exec node1 "admin.peers.length"'
  exit 1
fi

if [ "$#" -eq 2 ]; then
   GETH_CMD=$2
fi

if [ "$#" -eq 3 ]; then
   echo "setting namespace to $3"
   NAMESPACE="--namespace=$3"
fi

POD=$(kubectl get pods $NAMESPACE | grep Running | grep $1 |  awk '{print $1}')

if [ -z "$SILENT" ]; then
  echo "GETH_CMD [$GETH_CMD]"
  echo "executing geth command [$GETH_CMD] on POD [$POD]"
fi

kubectl $NAMESPACE exec -it $POD -c quorum -- /geth-helpers/geth-exec.sh "$GETH_CMD"
