#!/usr/bin/env ruby

require "yaml"
require "erb"
require 'colorize'

# generic variables
@config                = YAML.load_file("qubernetes.yaml")
@nodes                 = YAML.load_file("nodes.yaml")["nodes"]
@Raft_Port             = @config["quorum"]["quorum"]["Raft_Port"]
@Node_WSPort           = @config["geth"]["Node_WSPort"]
@NodeP2P_ListenAddr    = @config["geth"]["NodeP2P_ListenAddr"]

# If the namespace is set in the config, create it and add it to all the resources.
@Namespace = ""
if @config["namespace"] != nil
  if @config["namespace"]["name"] != ""
@Namespace = "namespace: " + @config["namespace"]["name"]
   end
end

# What kind of persistent storage is desired?
# Default to host, but if
@Storage_Type          = "Host"
if  @config["quorum"]["storage"] && @config["quorum"]["storage"]["Type"] == "PVC"
  @Storage_Type = "PVC"
end
#####################
# Create config files for each node
#####################

def set_node_template_vars(values)
  @Node_UserIdent        = values["Node_UserIdent"]
  return
end



# create the output directory if it doesn't exist
`mkdir -p out`

sed_string = ""

# make all services
# set the replacement string sed cmmand which is run on the permissioned-nodes.json,
# as the service host IPs of the nodes are not known until they are deployed, and need
# to be properly set in the permissioned-nodes.json.
#PERM_NODE_JSON=$(echo $PERM_NODE_TMPL | sed \"s/%QUORUM_DEPLOYMENT_01_SERVICE_HOST%/$QUORUM_NODE01_SERVICE_HOST/g\" | sed \"s/\\$QUORUM_DEPLOYMENT_02_SERVICE_HOST/$QUORUM_NODE02_SERVICE_HOST/g\");
@nodes.each do |node|
  set_node_template_vars(node.values.first)
#  puts ("#{@Node_UserIdent}")
  k8_service_host_var = ("#{@Node_UserIdent}".upcase + "_SERVICE_HOST").gsub("-", "_")
  permission_node_host="#{@Node_UserIdent}".upcase + "_SERVICE_HOST"
 # puts (k8_service_host_var)
  sed_instruction = ' sed \"s/%' + permission_node_host + '%/$' + k8_service_host_var + '/g\"'
  sed_string = sed_string + sed_instruction + " | "
end

@Sed_Set_Node_Service_Host = sed_string[0...-2]
#puts (sed_string)
if @Storage_Type == "PVC"
  File.open("out/00-quorum-persistent-volumes.yaml", "w") do |f|
    f.puts (ERB.new(File.read("persistent-volumes.yaml.erb"), nil, "-").result)
  end
end
File.open("out/01-quorum-shared-config.yaml", "w") do |f|
  f.puts (ERB.new(File.read("quorum-shared-config.yaml.erb"), nil, "-").result)
end

# Create the service resources
File.open("out/02-quorum-services.yaml", "w") do |f|
  f.puts (ERB.new(File.read("quorum-services.yaml.erb"), nil, "-").result)
end

# make all keystore resrouce (configMap, TODO: Secretes)
File.open("out/03-quorum-keyconfigs.yaml", "w") do |f|
  f.puts (ERB.new(File.read("quorum-keystore.yaml.erb"), nil, "-").result)
end

# make deployments
File.open("out/04-quorum-deployments.yaml", "w") do |f|
  f.puts (ERB.new(File.read("quorum-deployment.yaml.erb"), nil, "-").result)
end

puts("\n")
puts "  Success! ".green
puts("\n")
puts("  Quorum Kubernetes resource files have been generated in the `out/` directory.")
puts("\n")
puts("  Deploy to kubernetes:")
puts("\n")
puts("  $> kubectl apply -f out")
puts("\n")
