#!/usr/bin/env ruby

require "yaml"
require "erb"
require 'colorize'

# generic variables
@config                = YAML.load_file("qubernetes.yaml")
@nodes                 = YAML.load_file("nodes.yaml")["nodes"]
@Raft_Port             = @config["quorum"]["quorum"]["Raft_Port"]
@Node_WSPort           = @config["geth"]["Node_WSPort"]
@NodeP2P_ListenAddr    = @config["geth"]["NodeP2P_ListenAddr"]


# Generate deployments in a single file, or in separate files.
@sep_deployment_files=false
if @config["sep_deployment_files"] != nil
  @sep_deployment_files = @config["sep_deployment_files"]
end

# If the namespace is set in the config, create it and add it to all the resources.
@Namespace = ""
if @config["namespace"] != nil
  if @config["namespace"]["name"] != ""
@Namespace = "namespace: " + @config["namespace"]["name"]
   end
end

# What kind of persistent storage is desired?
# Default to host, but if
@Storage_Type          = "Host"
if  @config["quorum"]["storage"] && @config["quorum"]["storage"]["Type"] == "PVC"
  @Storage_Type = "PVC"
end
#####################
# Create config files for each node
#####################

def set_node_template_vars(values)
  @Node_UserIdent        = values["Node_UserIdent"]
  @Node_Key_Dir          = values["Key_Dir"]
  return
end


# create the output directory if it doesn't exist
`mkdir -p out`

sed_string = ""
sed_string_no_escape = ""

# make all services
# set the replacement string sed command which is run on the permissioned-nodes.json,
# as the service host IPs of the nodes are not known until they are deployed, and need
# to be properly set in the permissioned-nodes.json.
#PERM_NODE_JSON=$(echo $PERM_NODE_TMPL | sed \"s/%QUORUM_DEPLOYMENT_01_SERVICE_HOST%/$QUORUM_NODE01_SERVICE_HOST/g\" | sed \"s/\\$QUORUM_DEPLOYMENT_02_SERVICE_HOST/$QUORUM_NODE02_SERVICE_HOST/g\");
@nodes.each do |node|
  set_node_template_vars(node.values.first)
#  puts ("#{@Node_UserIdent}")
  k8_service_host_var = ("#{@Node_UserIdent}".upcase + "_SERVICE_HOST").gsub("-", "_")
  permission_node_host="#{@Node_UserIdent}".upcase + "_SERVICE_HOST"
 # puts (k8_service_host_var)
  sed_instruction = ' sed \"s/%' + permission_node_host + '%/$' + k8_service_host_var + '/g\"'
  sed_instruction_no_escape = ' sed "s/%' + permission_node_host + '%/$' + k8_service_host_var + '/g"'
  sed_string = sed_string + sed_instruction + " | "
  sed_string_no_escape = sed_string_no_escape + sed_instruction_no_escape + " | "
end

# used/written inside each generated deployment file.
@Sed_Set_Node_Service_Host = sed_string[0...-2]
# used inside cofigMap script
@Sed_Set_Node_Service_Host_No_Escape = sed_string_no_escape[0...-2]

#puts (sed_string)
if @Storage_Type == "PVC"
  File.open("out/00-quorum-persistent-volumes.yaml", "w") do |f|
    f.puts (ERB.new(File.read("persistent-volumes.yaml.erb"), nil, "-").result)
  end
end
File.open("out/01-quorum-genesis.yaml", "w") do |f|
  f.puts (ERB.new(File.read("quorum-genesis-config.yaml.erb"), nil, "-").result)
end
File.open("out/02-quorum-shared-config.yaml", "w") do |f|
  f.puts (ERB.new(File.read("quorum-shared-config.yaml.erb"), nil, "-").result)
end

# Create the service resources
File.open("out/03-quorum-services.yaml", "w") do |f|
  f.puts (ERB.new(File.read("quorum-services.yaml.erb"), nil, "-").result)
end

# make all keystore resrouce (configMap)
File.open("out/04-quorum-keyconfigs.yaml", "w") do |f|
  f.puts (ERB.new(File.read("quorum-keystore.yaml.erb"), nil, "-").result)
end

@Kubectl_Cmd="  $> kubectl apply -f out"
if @sep_deployment_files
 `mkdir -p out/deployments`
 ct=1
 @nodes.each do |node|
   set_node_template_vars(node.values.first)
   # create each deployment in a separate file.
   File.open("out/deployments/0" + ct.to_s + "-quorum-single-deployment.yaml", "w") do |f|
     f.puts (ERB.new(File.read("quorum-deployment.yaml.erb"), nil, "-").result)
   end
   ct = ct + 1
 end
 @Kubectl_Cmd="  $> kubectl apply -f out -f out/deployments"
else
  File.open("out/05-quorum-deployments.yaml", "w") do |f|
    f.puts("---")
  end
  @nodes.each do |node|
    set_node_template_vars(node.values.first)
    # create each deployment in a separate file.
    File.open("out/05-quorum-deployments.yaml", "a") do |f|
      f.puts (ERB.new(File.read("quorum-deployment.yaml.erb"), nil, "-").result)
      f.puts("---")
    end
  end
end



puts("\n")
puts "  Success! ".green
puts("\n")
puts("  Quorum Kubernetes resource files have been generated in the `out/` directory.")
puts("\n")
puts("  To deploy to kubernetes run:")
puts("\n")
puts(@Kubectl_Cmd)
puts("\n")
