#!/usr/bin/env ruby

require "yaml"
require "erb"
require 'optparse'

@base_template_path = "templates/config"
@quick_start_out_yaml = "quick-start.yaml"

# set up flag options
options = {consensus: 'istanbul', quorum_version: '2.6.0', tm_version: '0.10.4', tm_name: 'tessera', chain_id: '1000', num_nodes: 4}

OptionParser.new do |opts|
  opts.banner = "Usage: ./quick-start [options]"

  opts.on("-c", "--consensus[ACTION]", String,
          "The consensus to use for the network (raft or istanbul), default istanbul ") do |c|
    options[:consensus] = c
  end

  opts.on("-q", "--quorum-version[ACTION]", String,
          "The version of quorum to deploy, default 2.6.0") do |q|
    options[:quorum_version] = q
  end

  opts.on("-t", "--tm-version[ACTION]", String,
          "The version of the transaction manager to deploy, default 0.10.4") do |tm|
    options[:tm_version] = tm
  end

  opts.on("--tm-name[ACTION]", String,
          "The transaction manager (tessera|constellation) for the network, default tessera") do |tm|
    options[:tm_name] = tm
  end

  opts.on("-c", "--chain-id[ACTION]", String,
          "The chain id for the network manager deploy, default 1000") do |tm|
    options[:chain_id] = tm
  end

  opts.on("-n", "--num-nodes[ACTION]", Numeric,
          "The number of nodes to deploy, default 4") do |num|
    options[:num_nodes] = num
  end

  opts.on("-h", "--help", "prints this help.") do
    puts opts
    exit
  end

end.parse!

@consensus=options[:consensus]
@Quorum_Version=options[:quorum_version]
@Tm_Version=options[:tm_version]
@Tm_Name=options[:tm_name]
@Chain_Id=options[:chain_id]
@Num_Nodes=options[:num_nodes]
puts "consensus : " + @consensus
puts "quorum version : " + @Quorum_Version
puts "tm version : " + @Tm_Version
puts "tm name : " + @Tm_Name
puts "using chain id : " + @Chain_Id
puts "num nodes: " + @Num_Nodes.to_s


puts("generating " + @quick_start_out_yaml)
File.open(@quick_start_out_yaml , "w") do |f|
  f.puts (ERB.new(File.read(@base_template_path + "/qubernetes-quickstart.yaml.erb"), nil, "-").result)
end
