#!/usr/bin/env ruby

require "yaml"
require "erb"

@CONFIG_FILE = "qubernetes.yaml"
@OPTIONAL_CONFIG_FILE=ARGV[0]
ARGV.clear

if @OPTIONAL_CONFIG_FILE != nil
  @CONFIG_FILE = @OPTIONAL_CONFIG_FILE
end
puts "using config file: " + @CONFIG_FILE

@config     = YAML.load_file(@CONFIG_FILE)
@nodes      = YAML.load_file("nodes.yaml")["nodes"]

@base_template_path = "templates/quorum"

File.open(@base_template_path + "/gen-node-keys.sh", "w") do |f|
  f.puts (ERB.new(File.read(@base_template_path + "/gen-keys.sh.erb"), nil, "-").result)
end

`echo WE ARE HERE $(pwd)`
`chmod 755 #{@base_template_path}/gen-node-keys.sh`
`echo #{@base_template_path}/generating keys`
`./#{@base_template_path}/gen-node-keys.sh`
