#!/usr/bin/env ruby

require "yaml"
require "erb"

# generic variables
@config     = YAML.load_file("qubernetes.yaml")

File.open("out/config/nodes.yaml", "w") do |f|
  f.puts (ERB.new(File.read("nodes.yaml.erb"), nil, "-").result)
end

`rm nodes.yaml | true`
`ln -s out/config/nodes.yaml .`
