#!/usr/bin/env ruby

if File.directory?("out")
  puts("\n The 'out' directory already exist.")
  puts(" Please select the action you wish to take:")
  puts("")
  puts(" [1] Delete the 'out' directory and generate new resources.")
  puts(" [2] Update / add nodes that don't already exist.")
  puts(" [3] Cancel.")
  res = gets
  res = res.strip
  case res
  when "1"
    puts("Creating all new resources.")
    `rm -r out`
  when "2"
    puts("Generating additional resources only.")
  when "3"
    puts("OK, bye :)")
    exit(0)
  else
    puts("OK, not doing anything :)")
    exit(0)
  end
end

`
# create the output directory if
# it doesn't exist
mkdir -p out/config

# generate the nodes.yaml
# file for the set number of
# nodes.
./quorum-create-nodes

`
puts ""
puts "  Generating keys..."
`
# generate the keygen script
# to generate nodekey, account keys, and
# quorum transaction manger (tm.pub,tm.key) keys.
./quorum-keygen
`

puts "  Generating Quorum configs..."
`
# generate the appropriate config files:
#   permissioned-nodes.json
#   genesis.json 
./quorum-config
`

puts ""
puts  "  Base quorum resources have been generated. "
puts  "  Running ./qubernetes to generate Kubernetes resources."
puts ""
`
./qubernetes
`
puts "  Deploy Quorum Kubernetes resources:"
puts "  $> kubectl apply -f out"

