#!/usr/bin/env ruby

require "yaml"
require "erb"

# setup the config file to use to generate the quorum resources and kubernetes API resources.
@CONFIG_FILE = "qubernetes.yaml"
@OPTIONAL_CONFIG_FILE=ARGV[0]
ARGV.clear

if @OPTIONAL_CONFIG_FILE != nil
  @CONFIG_FILE = @OPTIONAL_CONFIG_FILE
end
puts "using config file: " + @CONFIG_FILE

@config                = YAML.load_file(@CONFIG_FILE)

if File.directory?("out") && !@config["skip_out_directory"]
  puts("\n The 'out' directory already exist.")
  puts(" Please select the action you wish to take:")
  puts("")
  puts(" [1] Delete the 'out' directory and generate new resources.")
  puts(" [2] Update / add nodes that don't already exist.")
  puts(" [3] Cancel.")
  res = gets
  res = res.strip
  case res
  when "1"
    puts("Creating all new resources.")
    `rm -r out`
  when "2"
    puts("Generating additional resources only.")
  when "3"
    puts("OK, bye :)")
    exit(0)
  else
    puts("OK, not doing anything :)")
    exit(0)
  end
end

`
# create the output directory if
# it doesn't exist
mkdir -p out/config
# generate the nodes.yaml
# file for the set number of
# nodes.
./quorum-create-nodes #{@CONFIG_FILE}
`
puts ""
puts "  Generating keys..."
`
# generate the keygen script
# to generate nodekey, account keys, and
# quorum transaction manger (tm.pub,tm.key) keys.
./quorum-keygen #{@CONFIG_FILE}
`

puts "  Generating Quorum configs..."
`
# generate the appropriate config files:
#   permissioned-nodes.json
#   genesis.json
./quorum-config #{@CONFIG_FILE}
`

puts ""
puts  "  Base quorum resources have been generated. "