#!/usr/bin/env ruby

require "yaml"
require "erb"

def set_node_template_vars(values)
  @Node_UserIdent        = values["Node_UserIdent"]
  @Node_Key_Dir          = values["Key_Dir"]
  return
end

@config_file = "qubernetes.yaml"
@optional_config_file=ARGV[0]
ARGV.clear

if @optional_config_file != nil
  @config_file = @optional_config_file
end
puts "using config file: " + @config_file

@config     = YAML.load_file(@config_file)
@nodes      = @config["nodes"]

@base_template_path = "templates/quorum"

# used by gen-keys.sh.erb
@Key_Dir_Base = "out/config"
if @config.dig("config","Key_Dir_Base")
  @Key_Dir_Base  = @config["config"]["Key_Dir_Base"]
end
puts "key dir is " + @Key_Dir_Base
File.open(@base_template_path + "/gen-node-keys.sh", "w") do |f|
  f.puts (ERB.new(File.read(@base_template_path + "/gen-keys.sh.erb"), nil, "-").result)
end

`echo WE ARE HERE $(pwd)`
`chmod 755 #{@base_template_path}/gen-node-keys.sh`
`echo #{@base_template_path}/generating keys`
`./#{@base_template_path}/gen-node-keys.sh`
