k8s:
  sep_deployment_files: true
  service:
    # NodePort | ClusterIP
    type: NodePort
  # persistent storage is handled by Persistent Volume Claims (PVC) https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  storage:
    PVC:
      annotations:
        volume.beta.kubernetes.io/storage-class: "YOUR_STORAGE_CLASS"
      ## when redeploying cannot be less than previous values
      Capacity: 1Gi

# quorum and node specific config
genesis:
  # supported: (raft | istanbul)
  consensus: istanbul
  Quorum_Version: 2.6.0
  Chain_Id: 10

# Add as many nodes as you wish below
# keys and config will be generated locally
nodes:

  -  Node_UserIdent: quorum-node1
     Key_Dir: key1
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 2.6.0
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 0.10.4

  -  Node_UserIdent: quorum-node2
     Key_Dir: key2
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 2.6.0
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 0.10.4

  -  Node_UserIdent: quorum-node3
     Key_Dir: key3
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 2.6.0
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 0.10.4

  -  Node_UserIdent: quorum-node4
     Key_Dir: key4
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 2.6.0
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 0.10.4
