#namespace:
#  name: quorum-test
# number of nodes to deploy
nodes:
  number: 4
quorum:
  # related to quorum containers
  quorum:
    # supported: (raft | istanbul)
    consensus: istanbul
    Quorum_Version: 2.4.0
  tm:
    # container images at https://hub.docker.com/u/quorumengineering/
    Name: tessera
    Tm_Version: 0.10.2
# generic geth related options
geth:
  network:
    id: 1101
    public: false
  # general verbosity of geth [1..5]
  verbosity: 9
  # additional startup params to pass into geth/quorum
  Geth_Startup_Params: --rpccorsdomain=\"*\"

k8s:
  sep_deployment_files: true
  service:
    # NodePort | ClusterIP
    type: NodePort
  # persistent storage is handled by Persistent Volume Claims (PVC) https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  storage:
    PVC:
      storageClass:
        # should exist under templates/k8s/storage-classes and be `yaml.erb` files, e.g. templates/k8s/storage-classes/ks-storage-class.yaml.erb
        template: eks-storage-class
        name: io1
        provisioner: kuberentes.io/aws-ebs
        kmsKeyId: arn:aws:kms:us-east-1:...
      storageClassName: io1
      ## when redeploying cannot be less than previous values
      Capacity: 1Gi
