nodes:
  number: 4
quorum:
  # related to quorum containers
  quorum:
    # supported: (raft | istanbul)
    consensus: istanbul
    # container images at https://hub.docker.com/u/quorumengineering/
    Quorum_Version: 2.6.0
  # related to transaction manager containers
  tm:
    # container images at https://hub.docker.com/u/quorumengineering/
    # (tessera|constellation)
    Name: tessera
    Tm_Version: 0.10.4
# generic geth related options
geth:
  Node_RPCPort: 8545
  NodeP2P_ListenAddr: 30303
  network:
    # network id (1: mainnet, 3: ropsten, 4: rinkeby ... )
    id: 1101
    # public (true|false) is it a public network?
    public: false
  # general verbosity of geth [1..5]
  verbosity: 9
  # additional startup params to pass into geth/quorum
  Geth_Startup_Params: --rpccorsdomain=\"*\"
k8s:
  service:
    # NodePort | ClusterIP
    type: NodePort
  # persistent storage is handled by Persistent Volume Claims (PVC) https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  storage:
    PVC:
      # optional storage class, if you don't know what this is,
      storageClassName: my-csi-plugin
      ## when redeploying cannot be less than previous values
      Capacity: 1Gi