nodes:
  number: 4
quorum:
  # related to quorum containers
  quorum:
    # supported: (raft | istanbul)
    consensus: istanbul
    # container images at https://hub.docker.com/u/quorumengineering/
    Quorum_Version: 2.6.0
  # related to transaction manager containers
  tm:
    # container images at https://hub.docker.com/u/quorumengineering/
    # (tessera|constellation)
    Name: tessera
    Tm_Version: 0.10.4
# generic geth related options
geth:
  network:
    # network id (1: mainnet, 3: ropsten, 4: rinkeby ... )
    id: 1101
  # general verbosity of geth [1..5]
  verbosity: 9
  # additional startup params to pass into geth/quorum
  Geth_Startup_Params: --rpccorsdomain=\"*\"

k8s:
  sep_deployment_files: true
  service:
    # NodePort | ClusterIP
    type: NodePort
    Ingress:
      # OneToMany | OneToOne
      Strategy: OneToOne
      Host: "quorum.testnet.com"
    NetworkPolicy: true
