# number of nodes to deploy
nodes:
  number: 4
quorum:
  # related to quorum containers
  quorum:
    # supported: (raft | istanbul)
    consensus: istanbul
    Quorum_Version: 2.6.0
    # the docker repo that hold your quorum container
    Docker_Repo: %%YOUR_CUSTOM_DOCKER_REPO%%
  # related to transaction manager containers
  tm:
    # (tessera|constellation)
    Name: tessera
    Tm_Version: 0.10.4
    # the docker repo that hold your quorum container
    Docker_Repo: %%YOUR_CUSTOM_DOCKER_REPO%%
# generic geth related options
geth:
  network:
    # network id (1: mainnet, 3: ropsten, 4: rinkeby ... )
    id: 1101
  # general verbosity of geth [1..5]
  verbosity: 9
  # additional startup params to pass into geth/quorum
  Geth_Startup_Params: --rpccorsdomain=\"*\"
k8s:
  sep_deployment_files: true
  service:
    # NodePort | ClusterIP
    type: NodePort
  # persistent storage is handled by Persistent Volume Claims (PVC) https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  # test locally and on GCP
  # The data dir is persisted here
  storage:
    # PVC (Persistent_Volume_Claim - tested with GCP).
    Type: PVC
    ## when redeploying cannot be less than previous values
    Capacity: 1Gi