#namespace:
#  name: quorum-test
# number of nodes to deploy
sep_deployment_files: true
nodes:
  number: 4
quorum:
  # base quorum data dir as set inside each container.
  Node_DataDir: /etc/quorum/qdata
  # This is where all the keys are store, and/or where they are generated, as in the case of quorum-keygen.
  # Either full or relative paths on the machine generating the config
  Key_Dir_Base: out/config
  Permissioned_Nodes_File: out/config/permissioned-nodes.json
  Genesis_File: out/config/genesis.json
  # related to quorum containers
  quorum:
    # supported: (raft | istanbul)
    consensus: istanbul
    Quorum_Version: 2.4.0
    # the docker repo that hold your quorum container
    Docker_Repo: %%YOUR_CUSTOM_DOCKER_REPO%%
  # related to transaction manager containers
  tm:
    # (tessera|constellation)
    Name: tessera
    Tm_Version: 0.10.2
    # the docker repo that hold your quorum container
    Docker_Repo: %%YOUR_CUSTOM_DOCKER_REPO%%
    Port: 9001
    3Party_Port: 9080
    Tessera_Config_Dir: out/config
# generic geth related options
geth:
  Node_RPCPort: 8545
  NodeP2P_ListenAddr: 30303
  network:
    # network id (1: mainnet, 3: ropsten, 4: rinkeby ... )
    id: 1101
    # public (true|false) is it a public network?
    public: false
  # general verbosity of geth [1..5]
  verbosity: 9
  # additional startup params to pass into geth/quorum
  Geth_Startup_Params: --rpccorsdomain=\"*\"
k8s:
  service:
    # NodePort | ClusterIP
    type: NodePort
  # persistent storage is handled by Persistent Volume Claims (PVC) https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  # test locally and on GCP
  # The data dir is persisted here
  storage:
    # PVC (Persistent_Volume_Claim - tested with GCP).
    Type: PVC
    ## when redeploying cannot be less than previous values
    Capacity: 5Gi