k8s:
  sep_deployment_files: true
  # optionally  allow a security context to be set for the deployment, e.g. can the user have root access?
  securityContext:
    runAsUser: 430
    fsGroup: 430
    supplementalGroups: [666,777]
  service:
    # NodePort | ClusterIP | LoadBalancer
    type: NodePort
    Ingress:
      # OneToMany | OneToOne
      Strategy: OneToOne
      Host: "quorum.testnet.com"
    # persistent storage is handled by Persistent Volume Claims (PVC) https://kubernetes.io/docs/concepts/storage/persistent-volumes/
    # test locally and on GCP
    # The data dir is persisted here
    storage:
      # PVC (Persistent_Volume_Claim - tested with GCP).
      Type: PVC
      ## when redeploying cannot be less than previous values
      Capacity: 200Mi

cakeshop:
  version: 0.12.1
  service:
    type: NodePort
    nodePort: 30108

# monitor will enable prometheus geth monitoring, grafana is kept external for now.
prometheus:
  # override the default monitor startup params --metrics --metrics.expensive --pprof --pprofaddr=0.0.0.0.
  #monitor_params_geth: --metrics --metrics.expensive --pprof --pprofaddr=0.0.0.0
  nodePort_prom: 31323

# quorum and node specific config
genesis:
  # supported: (raft | istanbul)
  consensus: istanbul
  Quorum_Version: 21.7.1
  Tm_Version: 21.7.2
  Chain_Id: 10

# Add as many nodes as you wish below
# keys and config will be generated locally
nodes:

  -  Node_UserIdent: quorum-node1
     Key_Dir: key1
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 21.7.1
         Docker_Repo: MY_DOCKER_REPO
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 21.7.2
         Docker_Repo: MY_DOCKER_REPO
     geth:
       network:
         # network id (1: mainnet, 3: ropsten, 4: rinkeby ... )
         id: 1101
       verbosity: 9
       Geth_Startup_Params: --rpccorsdomain=\"*\"

  -  Node_UserIdent: quorum-node2
     Key_Dir: key2
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 21.7.1
         # the docker repo that hold your quorum container
         Docker_Repo: MY_DOCKER_REPO
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 21.7.2
         # the docker repo that hold your quorum container
         Docker_Repo: MY_DOCKER_REPO
     geth:
       Geth_Startup_Params: --rpccorsdomain=\"*\"

  -  Node_UserIdent: quorum-node3
     Key_Dir: key3
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 21.7.1
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 21.7.2
     geth:
       Geth_Startup_Params: --rpccorsdomain=\"*\"

  -  Node_UserIdent: quorum-node4
     Key_Dir: key4
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 21.7.1
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 21.7.2
