k8s:
  # optionally  allow a security context to be set for the deployment, e.g. can the user have root access?
  securityContext:
    runAsUser: 430
    fsGroup: 430
    supplementalGroups: [666,777]
  service:
    # NodePort | ClusterIP | LoadBalancer
    type: NodePort
    Ingress:
      # OneToMany | OneToOne
      Strategy: OneToOne
      Host: "quorum.testnet.com"
    # persistent storage is handled by Persistent Volume Claims (PVC) https://kubernetes.io/docs/concepts/storage/persistent-volumes/
    # test locally and on GCP
    # The data dir is persisted here
    storage:
      # PVC (Persistent_Volume_Claim - tested with GCP).
      Type: PVC
      ## when redeploying cannot be less than previous values
      Capacity: 200Mi
# quorum and node specific config
genesis:
  # supported: (raft | istanbul)
  consensus: istanbul
  Quorum_Version: 21.7.1
  Tm_Version: 21.7.2
  Chain_Id: 10

# Add as many nodes as you wish below
# keys and config will be generated locally
nodes:

  -  Node_UserIdent: quorum-node1
     Key_Dir: key1
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 21.7.1
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 21.7.2

  -  Node_UserIdent: quorum-node2
     Key_Dir: key2
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 21.7.1
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 21.7.2

  -  Node_UserIdent: quorum-node3
     Key_Dir: key3
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 21.7.1
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 21.7.2

  -  Node_UserIdent: quorum-node4
     Key_Dir: key4
     quorum:
       quorum:
         # supported: (raft | istanbul)
         consensus: istanbul
         Quorum_Version: 21.7.1
       tm:
         # (tessera|constellation)
         Name: tessera
         Tm_Version: 21.7.2
