# Build Geth in a stock Go builder container
# docker build -t quorum-base-local -f Dockerfile.gethbase .
FROM golang:1.13-alpine

RUN apk add --no-cache make gcc musl-dev linux-headers git ca-certificates

ADD . /go-ethereum
RUN cd /go-ethereum && make geth