
---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node1
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node1
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node1-deployment
  # NodePort | ClusterIP | Loadbalancer
  type: ClusterIP
  ports:
    # default 8545
    - name: rpc-listener
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: wsport
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401

---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node2
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node2
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node2-deployment
  # NodePort | ClusterIP | Loadbalancer
  type: ClusterIP
  ports:
    # default 8545
    - name: rpc-listener
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: wsport
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401

---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node3
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node3
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node3-deployment
  # NodePort | ClusterIP | Loadbalancer
  type: ClusterIP
  ports:
    # default 8545
    - name: rpc-listener
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: wsport
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401

---
apiVersion: v1
kind: Service
metadata:
  
  name: quorum-node4
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node4
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node4-deployment
  # NodePort | ClusterIP | Loadbalancer
  type: ClusterIP
  ports:
    # default 8545
    - name: rpc-listener
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: wsport
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: raft
      protocol: TCP
      targetPort: 50401
      port: 50401
