# Workflow to build the docker container and push to dockerhub
#
# 1. Uses https://github.com/docker/build-push-action
#   a. builds and pushes docker image to quorumengineering/qubernetes on push to master
#   b. action allows labeling of container, tagging as latest, using secrets for docker username and password

name: Docker Container Build

# Controls when the action will run. Triggers the workflow on all push events to the master branch
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push: [ master ]


jobs:
  # This workflow contains a single job called "docker-build"
  docker-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out qubernetes under $GITHUB_WORKSPACE, so this job can access it
      - uses: actions/checkout@v2
        name: Check out code
      # Uses existing dockerhub action to build and push image: https://github.com/docker/build-push-action
      - uses: docker/build-push-action@v1
        name: Build and Push Docker image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: quorumengineering/qubernetes
          tags: latest
          add_git_labels: true

